# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aad2cbaf6aacc8043d03e3a11f66d44c1e04f6598f28809e01054acbe7cdc5a6af6e27373d55da7af5287096806d7fc6bd2addfae74eff448430c653b1d08aac

test:
  secret_key_base: b37965db1467f9b8fa64cacff46989b0248bb120b62a00e4b4acdd309bdd1fec2120078a1a2a6a198ad414edc2cad874528c9474bda88b6129896961b1135f4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
